<?php

return [
    [
        'name' => 'version',
        'title' => 'API版本(请勿修改该值)',
        'type' => 'radio',
        'content' => [],
        'value' => 'v2',
        'rule' => '',
        'msg' => '',
        'tip' => 'V2版本只支持微信支付V2密钥，V3版本只支持微信支付V3密钥，请勿修改该值！！！',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wechat',
        'title' => '微信',
        'type' => 'array',
        'content' => [],
        'value' => [
            'appid' => '',
            'app_id' => '',
            'app_secret' => '',
            'miniapp_id' => 'wx3a708b76e9f65456',
            'mch_id' => '1695708291',
            'key' => 'zjzzkcbg20260212zjzzkcbg20260212',
            'key_v3' => '',
            'mode' => 'normal',
            'sub_mch_id' => '',
            'sub_appid' => '',
            'sub_app_id' => '',
            'sub_miniapp_id' => '',
            'notify_url' => '',
            'cert_client' => '/addons/epay/certs/apiclient_cert.pem',
            'cert_key' => '/addons/epay/certs/apiclient_key.pem',
            'log' => '1',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '微信参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'alipay',
        'title' => '支付宝',
        'type' => 'array',
        'content' => [],
        'value' => [
            'mode' => 'normal',
            'pid' => '',
            'app_id' => '',
            'notify_url' => '/addons/epay/api/notifyx/type/alipay',
            'return_url' => '/addons/epay/api/returnx/type/alipay',
            'private_key' => '',
            'signtype' => 'cert',
            'ali_public_key' => '',
            'app_cert_public_key' => '',
            'alipay_root_cert' => '',
            'log' => '1',
            'scanpay' => '0',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '支付宝参数配置',
        'ok' => '',
        'extend' => '',
    ],
];
